<style>
.ui-widget {
	top: -200px;
}
</style>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.detail", 
	"country", 
	array(
		"IBLOCK_TYPE" => "otpusk",
		"IBLOCK_ID" => "12",
		"ELEMENT_ID" => "",
		"ELEMENT_CODE" => $CODE,
		"CHECK_DATES" => "Y",
		"FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "DETAIL_TEXT",
			2 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "CN_NAME_chego",
			1 => "CN_NAME_kuda",
			2 => "CN_NAME_chemu",
			3 => "CN_NAME_gde",
			4 => "CN_KEY",
			5 => "TI_COKEY",
			6 => "CN_CODE",
			7 => "GEOGRAFY",
			8 => "CLIMATE",
			9 => "KITCHEN",
			10 => "POPULATION",
			11 => "DESCRIPTION_TOP",
			12 => "LANGUAGE",
			13 => "MAP",
			14 => "CN_NAMELAT",
			15 => "LABEL_TO_TOP",
			16 => "REGION",
			17 => "PRICE_MIN",
			18 => "PICTURES",
			19 => "",
		),
		"IBLOCK_URL" => "/countries/",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "Y",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"USE_PERMISSIONS" => "N",
		"PAGER_TEMPLATE" => "",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Страница",
		"PAGER_SHOW_ALL" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"USE_SHARE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "country",
		"DETAIL_URL" => "",
		"SET_CANONICAL_URL" => "Y",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"STRICT_SECTION_CHECK" => "N",
		"FILTER_NAME" => "arrFilter"
	),
	false,
	array(
		"ACTIVE_COMPONENT" => "Y"
	)
);?>
