<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Корпоративные экскурсии по Беларуси");
$APPLICATION->SetPageProperty("description", "Экскурсионные туры для корпоративных клиентов по Беларуси");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/biznesu/korporativnye-ekskursii/korporativnye-ekskursii-po-belarusi/");
$APPLICATION->SetTitle("Корпоративные экскурсии по Беларуси");
?><h3>Корпоративные экскурсии по Беларуси</h3>
 <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.tours.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_101" => "-",
		"ADD_PROPERTY_102" => "-",
		"ADD_PROPERTY_110" => "N",
		"ADD_PROPERTY_182" => "-",
		"ADD_PROPERTY_95" => "-",
		"ADD_PROPERTY_96" => "-",
		"ADD_PROPERTY_97_max" => "",
		"ADD_PROPERTY_97_min" => "",
		"ADD_PROPERTY_ID" => array(
			0 => "61969",
			1 => "61987",
			2 => "61990",
			3 => "61996",
			4 => "62032",
			5 => "62695",
			6 => "62697",
			7 => "66503",
			8 => "66519",
			9 => "66522",
			10 => "66780",
			11 => "66809",
			12 => "66811",
		),
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "18",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "POINT_DEPARTURE",
			2 => "TOWN",
			3 => "ROUTE",
			4 => "DEPARTURE",
			5 => "DEPARTURE_TEXT",
			6 => "FOOD",
			7 => "DAYS",
			8 => "PROVIDER",
			9 => "DEPARTURE_EXC_TEXT",
			10 => "DURATION",
			11 => "DURATION_TIME",
			12 => "TOURTYPE",
			13 => "TRANSPORT",
			14 => "TYPE_EXCURSIONS",
			15 => "THEME_TOURS",
			16 => "NMAN",
			17 => "SIGHTS",
			18 => "EXCURSIONS",
			19 => "HOTEL",
			20 => "PRICE",
			21 => "PRICE_CHILD",
			22 => "CURRENCY",
			23 => "DISCOUNT",
			24 => "HD_DESC",
			25 => "ADDITIONAL",
			26 => "TOUR_TYPE",
			27 => "NEW",
			28 => "FREE",
			29 => "MT_ID",
			30 => "PRICE_INCLUDE",
			31 => "PRICE_NO_INCLUDE",
			32 => "DOCUMENT",
			33 => "MT_KEY",
			34 => "DURATION_DAYS",
			35 => "MEDICINE",
			36 => "SHOW_ON_MAIN",
			37 => "TYPE_PERMIT",
			38 => "PRICE_FOR",
			39 => "PICTURES",
			40 => "",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => "seo.tours.list"
	),
	false
);?><br>
<p>
	 Приглашаем Вашу организацию и ее сотрудников посетить города Беларуси и насладиться неповторимой красотой белорусского края. Мы работаем для Вас и поэтому стараемся сделать экскурсионные туры максимально комфортными и интересными. По Вашему желанию мы сделаем рассадку в автобусе и расселение в гостинице, организуем обед или ужин. Отправление автобуса — от Вашего предприятия или с любого удобного для Вас места.&nbsp;
</p>
<p>
	 Выбирайте экскурсии из нашего каталога, заказывайте и путешествуйте!
</p>
<p>
</p>
<h5>Примечание:</h5>
<ul>
	<li><i class="fa fa-check-circle text-primary"></i> Оплата за тур производится за наличный или безналичный расчет.</li>
	<li><i class="fa fa-check-circle text-primary"></i> В группе должно быть не менее 40 туристов.</li>
	<li><i class="fa fa-check-circle text-primary"></i> В стоимость входят транспортные услуги и услуги экскурсовода.</li>
	<li><i class="fa fa-check-circle text-primary"></i> Экскурсионное обслуживание в музеях и входные билеты оплачиваются дополнительно в зависимости от возрастной категории экскурсантов (дети/взрослые).</li>
	<li><i class="fa fa-check-circle text-primary"></i> Питание (обед) на маршруте оплачивается дополнительно.</li>
</ul><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>