<?define('SHOW_BREADCRUMB', true);
define('NOT_FLOAT_RIGHT', true)?>
 <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
?> 
<?
if ($_REQUEST["ELEMENT_CODE"]) {

	$arElement = CIBlockElement::GetList(false, array('CODE' => $_REQUEST["ELEMENT_CODE"]))->Fetch();
	if ($arElement['ACTIVE_TO'] && time() >= MakeTimeStamp($arElement['ACTIVE_TO'])) {
		LocalRedirect('/tury/', false, "301 Moved permanently");
	}
}
?>
<?$elementID = $APPLICATION->IncludeComponent(
	"bitrix:catalog.element", 
	".default", 
	array(
		"TEMPLATE_THEME" => "blue",
		"DISPLAY_NAME" => "Y",
		"DETAIL_PICTURE_MODE" => "IMG",
		"ADD_DETAIL_TO_SLIDER" => "Y",
		"ADD_PICT_PROP" => "-",
		"LABEL_PROP" => "-",
		"DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_CLOSE_POPUP" => "Y",
		"DISPLAY_COMPARE" => "N",
		"COMPARE_PATH" => "",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_BTN_COMPARE" => "Сравнить",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"USE_VOTE_RATING" => "N",
		"USE_COMMENTS" => "N",
		"BRAND_USE" => "N",
		"IBLOCK_TYPE" => "otpusk",
		"IBLOCK_ID" => "18",
		"ELEMENT_ID" => "",
		"ELEMENT_CODE" => $_REQUEST["ELEMENT_CODE"],
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_URL" => "#SITE_DIR#/tury/",
		"DETAIL_URL" => "#SITE_DIR#/tury/#ELEMENT_CODE#/",
		"BASKET_URL" => "",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"CHECK_SECTION_ID_VARIABLE" => "N",
		"SEF_MODE" => "Y",
		"SET_TITLE" => "Y",
		"SET_CANONICAL_URL" => "Y",
		"SHOW_DEACTIVATED" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"BROWSER_TITLE" => "-",
		"SET_META_KEYWORDS" => "Y",
		"META_KEYWORDS" => "-",
		"SET_META_DESCRIPTION" => "Y",
		"META_DESCRIPTION" => "-",
		"SET_LAST_MODIFIED" => "Y",
		"USE_MAIN_ELEMENT_SECTION" => "Y",
		"SET_STATUS_404" => "Y",
		"SHOW_404" => "Y",
		"MESSAGE_404" => "",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_ELEMENT_CHAIN" => "Y",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "POINT_DEPARTURE",
			2 => "TOWN",
			3 => "ROUTE",
			4 => "DEPARTURE",
			5 => "DEPARTURE_TEXT",
			6 => "FOOD",
			7 => "DAYS",
			8 => "DEPARTURE_EXC_TEXT",
			9 => "DURATION",
			10 => "DURATION_TIME",
			11 => "TOURTYPE",
			12 => "TRANSPORT",
			13 => "TYPE_EXCURSIONS",
			14 => "THEME_TOURS",
			15 => "NMAN",
			16 => "SIGHTS",
			17 => "EXCURSIONS",
			18 => "HOTEL",
			19 => "PRICE",
			20 => "PRICE_CHILD",
			21 => "CURRENCY",
			22 => "DISCOUNT",
			23 => "ADDITIONAL",
			24 => "TOUR_TYPE",
			25 => "NEW",
			26 => "MT_ID",
			27 => "PRICE_INCLUDE",
			28 => "PRICE_NO_INCLUDE",
			29 => "DOCUMENT",
			30 => "MEDICINE",
			31 => "SHOW_ON_MAIN",
			32 => "TYPE_PERMIT",
			33 => "NDAYS",
			34 => "BYR_PRICE",
			35 => "",
		),
		"OFFERS_FIELD_CODE" => "",
		"OFFERS_PROPERTY_CODE" => "",
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "name",
		"OFFERS_SORT_ORDER2" => "desc",
		"OFFERS_LIMIT" => "0",
		"BACKGROUND_IMAGE" => "-",
		"PRICE_CODE" => array(
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "N",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_PROPERTIES" => array(
		),
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "Y",
		"LINK_IBLOCK_TYPE" => "",
		"LINK_IBLOCK_ID" => "",
		"LINK_PROPERTY_SID" => "",
		"LINK_ELEMENTS_URL" => "",
		"SET_VIEWED_IN_COMPONENT" => "N",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"CACHE_TYPE" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_NOTES" => "",
		"CACHE_GROUPS" => "Y",
		"USE_ELEMENT_COUNTER" => "Y",
		"HIDE_NOT_AVAILABLE" => "N",
		"GIFTS_DETAIL_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_DETAIL_TEXT_LABEL_GIFT" => "Подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_BLOCK_TITLE" => "Выберите один из товаров, чтобы получить подарок",
		"GIFTS_MAIN_PRODUCT_DETAIL_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_MAIN_PRODUCT_DETAIL_PAGE_ELEMENT_COUNT" => "3",
		"GIFTS_MESS_BTN_BUY" => "Выбрать",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"USE_GIFTS_DETAIL" => "Y",
		"USE_GIFTS_MAIN_PR_SECTION_LIST" => "Y",
		"OFFERS_CART_PROPERTIES" => "",
		"ADD_TO_BASKET_ACTION" => array(
			0 => "BUY",
			1 => "ADD",
		),
		"SHOW_BASIS_PRICE" => "N",
		"CONVERT_CURRENCY" => "Y",
		"CURRENCY_ID" => "RUB",
		"QUANTITY_FLOAT" => "N",
		"COMPONENT_TEMPLATE" => ".default",
		"FILE_404" => "",
		"SEF_RULE" => "/tury/#ELEMENT_CODE#/",
		"SECTION_CODE_PATH" => "",
		"PLACEMENT_URL" => "#SITE_DIR##SEF_FOLDER##ELEMENT_CODE#/"
	),
	false
);?>

 <?$GLOBALS['arrFilter']['PROPERTY_ELEMENT_ID'] = $elementID > 0 ? $elementID : -1;?> <?$APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"review-list",
	Array(
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"COMPONENT_TEMPLATE" => "review-list",
		"DETAIL_URL" => "",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_DATE" => "N",
		"DISPLAY_NAME" => "N",
		"DISPLAY_PICTURE" => "N",
		"DISPLAY_PREVIEW_TEXT" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"FIELD_CODE" => array(0=>"ID",1=>"NAME",2=>"DETAIL_TEXT",3=>"DATE_ACTIVE_FROM",4=>"",),
		"FILTER_NAME" => "arrFilter",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "59",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"INCLUDE_SUBSECTIONS" => "N",
		"MESSAGE_404" => "",
		"NEWS_COUNT" => "1",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Новости",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"PREVIEW_TRUNCATE_LEN" => "",
		"PROPERTY_CODE" => array(0=>"EMAIL",1=>"RATING",2=>"ELEMENT_ID",3=>"MORE_PHOTO",4=>"",),
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC"
	)
);?><?/*$APPLICATION->IncludeComponent(
	"bitrix:iblock.element.add.form",
	"review-form",
	Array(
		"COMPONENT_TEMPLATE" => "review-form",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
		"CUSTOM_TITLE_DETAIL_PICTURE" => "",
		"CUSTOM_TITLE_DETAIL_TEXT" => "Ваше сообщение",
		"CUSTOM_TITLE_IBLOCK_SECTION" => "",
		"CUSTOM_TITLE_NAME" => "Имя",
		"CUSTOM_TITLE_PREVIEW_PICTURE" => "",
		"CUSTOM_TITLE_PREVIEW_TEXT" => "",
		"CUSTOM_TITLE_TAGS" => "",
		"DEFAULT_INPUT_SIZE" => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR" => "N",
		"ELEMENT_ASSOC" => "CREATED_BY",
		"ELEMENT_ASSOC_PROPERTY" => "",
		"GROUPS" => array(0=>"2",),
		"IBLOCK_ID" => "59",
		"IBLOCK_TYPE" => "otpusk",
		"LEVEL_LAST" => "N",
		"LINK_ELEMENT_ID" => $elementID,
		"LIST_URL" => "",
		"MAX_FILE_SIZE" => "0",
		"MAX_LEVELS" => "",
		"MAX_USER_ENTRIES" => "",
		"PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
		"PROPERTY_CODES" => array(0=>"331",1=>"332",2=>"333",3=>"334",4=>"NAME",5=>"DETAIL_TEXT",),
		"PROPERTY_CODES_REQUIRED" => array(0=>"331",1=>"334",2=>"NAME",3=>"DETAIL_TEXT",),
		"RESIZE_IMAGES" => "N",
		"SEF_MODE" => "N",
		"STATUS" => "INACTIVE",
		"STATUS_NEW" => "NEW",
		"USER_MESSAGE_ADD" => "Спасибо. Ваш отзыв принят и будет рассмотрен модератором в ближайшее время. ",
		"USER_MESSAGE_EDIT" => "",
		"USE_CAPTCHA" => "N"
	)
);*/?> <br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>