<?
define('HIDE_COUNTRY_IN_FILTER', true);
define('HIDE_RESET_IN_FILTER', true);
?> <?
// принудительна установка фильтра по Беларуси
$_GET['set_filter'] = "Y";
$_GET['arrFilter_61_2545945474'] = "Y";
//////////////////////////////////////////////
?> <?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/otdykh-v-belarusi/gostinnitsy/");
$APPLICATION->SetTitle("Гостиницы");
?>
<p style="text-align: justify;">
	 Наша компания бронирует гостиницы Минска и других городов Беларуси&nbsp;по выгодным ценам, также мы предлагаем разные виды скидок. Выберите гостиницу, в которой Вам бы хотелось остановиться, и звоните нам по телефонам: +375 (17) 220-22-22, 226-99-71 или присылайте заявку в произвольной форме к нам на e-mail:<a href="mailto:incoming@belintourist.by">incoming@belintourist.by</a>. Также Вы можете забронировать гостиницы через форму обратной связи, которая придет на e-mail сотруднику по данному направлению, и он обязательно свяжется с Вами.
</p>
 <br>
 <?$GLOBALS['arrFilter']["!PROPERTY_60"] = 25?> <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section",
	"hotel-list",
	Array(
		"ACTION_VARIABLE" => "",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "N",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COMPONENT_TEMPLATE" => "hotel-list",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "SORT",
		"ELEMENT_SORT_FIELD2" => "RAND",
		"ELEMENT_SORT_ORDER" => "ASC",
		"ELEMENT_SORT_ORDER2" => "RAND",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "",
		"MESS_BTN_BUY" => "",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "",
		"MESS_NOT_AVAILABLE" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "0",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "modern",
		"PAGER_TITLE" => "",
		"PAGE_ELEMENT_COUNT" => "24",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "N",
		"PRODUCT_ID_VARIABLE" => "",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(0=>"COUNTRY",1=>"TOWN",2=>"TYPE_ID",3=>"CAT_ID",4=>"HD_ADDRESS",5=>"HD_ADDRESS_COUNTRY_LANGUAGE",6=>"HD_PHONE",7=>"HD_FAX",8=>"HD_EMAIL",9=>"HD_HTTP",10=>"MAP",11=>"CURRENCY_BY",12=>"PRICE_MIN_BY",13=>"PRICE_MIN_RU",14=>"CURRENCY_RU",15=>"MAP_SCALE",16=>"SEARCH",17=>"MEDPROFIL",18=>"NATIONAL_PARK",19=>"HD_DESC",20=>"PROEZD",21=>"SPORTS_COMPLEX",22=>"PRICE_TEXT",23=>"HD_DESCROOM",24=>"HD_DESCMEAL",25=>"HD_DESCSERVICE",26=>"HD_DESCSPORT",27=>"HD_DESCSHEALTH",28=>"HD_DESCCHILD",29=>"HD_DESCBEACH",30=>"MEDICAL_TREATMENT",31=>"TYPE_PERMIT",32=>"HD_ADDINFORMATION",33=>"VODEO",34=>"DEPARTURE",35=>"DEPARTURE_TEXT",36=>"FOOD",37=>"DAYS",38=>"TOURTYPE",39=>"TRANSPORT",40=>"HOTEL",41=>"PRICE",42=>"CURRENCY",43=>"DISCOUNT",44=>"ADDITIONAL",45=>"TOUR_TYPE",46=>"NEW",47=>"MT_ID",48=>"PRICE_INCLUDE",49=>"PRICE_NO_INCLUDE",50=>"DAILY",51=>"MEDICINE",52=>"DOCUMENT",53=>"NDAYS",54=>"ACCOMODATIONS",55=>"POINT_DEPARTURE",56=>"",),
		"SECTION_CODE" => "",
		"SECTION_ID" => "168",
		"SECTION_ID_VARIABLE" => "",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"",1=>"",),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "",
		"TEMPLATE_THEME" => "",
		"TITLE_TEXT" => "Отели, гостиницы, средства размещения",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?> <?/*$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.hotels.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "-",
		"ADD_PROPERTY_61" => "69",
		"ADD_PROPERTY_62" => "-",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "seo.hotels.list",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"DISPLAY_TOP_PAGER" => "Y",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "TOWN",
			2 => "TYPE_ID",
			3 => "CAT_ID",
			4 => "PRICE_MIN_BY",
			5 => "PRICE_MIN_RU",
			6 => "CURRENCY_RU",
			7 => "SEARCH",
			8 => "PICTURES",
			9 => "",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => "168",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	),
	false
);*/?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>