<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("keywords", "Отдых Затока, Одесса 2019");
$APPLICATION->SetPageProperty("description", "Отдых в Украине от компании \"ЦЕНТРКУРОРТ\". Отдых для всей семьи, звоните +375 (17) 215-49-49.");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/tury/otdykh-zatoka-odessa-2018/");
$APPLICATION->SetTitle("Отдых Затока, Одесса 2019");
?>Предложения на отдых в Затоке в 2019 году формируются.<br>
 <br>
 <b><span style="color: #f16522;">ОТДЫХ В ЗАТОКЕ</span><br>
 </b><br>
 <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section",
	"seo.hotels.list",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "-",
		"ADD_PROPERTY_61" => "115",
		"ADD_PROPERTY_62" => "82925",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array("MT_HOTELKEY","PRICE_MIN_BY","PRICE_MIN_RU","VETLIVA_KEY","MT_KEY"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array("COUNTRY","TOWN","TYPE_ID","CAT_ID","CURRENCY_BY","CURRENCY_RU","SEARCH","MEDPROFIL","NATIONAL_PARK","NOT_SHOW_MT","REGIONS","SPORTS_COMPLEX","RF_PRICE_TYPE","FOREIGN_PRICE_TYPE","TYPE_PERMIT"),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("","COUNTRY","TOWN","TYPE_ID","CAT_ID","HD_ADDRESS","MT_HOTELKEY","HD_ADDRESS_COUNTRY_LANGUAGE","HD_PHONE","HD_FAX","HD_EMAIL","HD_HTTP","MAP","CURRENCY_BY","PRICE_MIN_BY","PRICE_MIN_RU","CURRENCY_RU","MAP_SCALE","SEARCH","VIDEO","MEDPROFIL","VETLIVA_KEY","MT_KEY","CONFERENCE_HALL","NATIONAL_PARK","NOT_SHOW_MT","REGIONS","HD_DESC","PROEZD","SPORTS_COMPLEX","CANCELLATION","RF_PRICE_TYPE","FOREIGN_PRICE_TYPE","PRICE_TEXT","HD_DESCROOM","HD_DESCMEAL","HD_DESCSERVICE","HD_DESCSPORT","HD_DESCSHEALTH","HD_DESCCHILD","HD_DESCBEACH","MEDICAL_TREATMENT","TYPE_PERMIT","HD_ADDINFORMATION",""),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array("",""),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?><br>
 <br>
 <b><span style="color: #f16522;">ОТДЫХ В ОДЕССЕ<br>
 </span></b><b><span style="color: #f16522;"><br>
 </span></b><?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section",
	"seo.hotels.list",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "23",
		"ADD_PROPERTY_61" => "115",
		"ADD_PROPERTY_62" => "603",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array("MT_HOTELKEY","PRICE_MIN_BY","PRICE_MIN_RU","VETLIVA_KEY","MT_KEY"),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array("COUNTRY","TOWN","TYPE_ID","CAT_ID","CURRENCY_BY","CURRENCY_RU","SEARCH","MEDPROFIL","NATIONAL_PARK","NOT_SHOW_MT","REGIONS","SPORTS_COMPLEX","RF_PRICE_TYPE","FOREIGN_PRICE_TYPE","TYPE_PERMIT"),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array("COUNTRY","TOWN","TYPE_ID","CAT_ID","HD_ADDRESS","MT_HOTELKEY","HD_ADDRESS_COUNTRY_LANGUAGE","HD_PHONE","HD_FAX","HD_EMAIL","HD_HTTP","MAP","CURRENCY_BY","PRICE_MIN_BY","PRICE_MIN_RU","CURRENCY_RU","MAP_SCALE","SEARCH","VIDEO","MEDPROFIL","VETLIVA_KEY","MT_KEY","CONFERENCE_HALL","NATIONAL_PARK","NOT_SHOW_MT","REGIONS","HD_DESC","PROEZD","SPORTS_COMPLEX","CANCELLATION","RF_PRICE_TYPE","FOREIGN_PRICE_TYPE","PRICE_TEXT","HD_DESCROOM","HD_DESCMEAL","HD_DESCSERVICE","HD_DESCSPORT","HD_DESCSHEALTH","HD_DESCCHILD","HD_DESCBEACH","MEDICAL_TREATMENT","TYPE_PERMIT","HD_ADDINFORMATION",""),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array("",""),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>