<?
$PERM["index.php"]["2"]="D";
$PERM["index.php"]["5"]="R";
$PERM["index.php"]["3"]="D";
$PERM["index.php"]["4"]="D";
$PERM["payment"]["2"]="D";
$PERM["payment"]["5"]="R";
$PERM["payment"]["3"]="D";
$PERM["payment"]["4"]="D";
?>