<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("canonical", "programmy-dla-detey");
$APPLICATION->SetPageProperty("keywords_inner", "медицинские программы, дети в санаториях, санатории беларуси для детей, детские санатории");
$APPLICATION->SetPageProperty("title", "Программы для детей в санаториях Беларуси");
$APPLICATION->SetPageProperty("description", "Программы для детей в санаториях Беларуси");
$APPLICATION->SetTitle("Программы для детей");?><?$GLOBAL["tours_filter"] = ["PROPERTY_COUNTRY" => "69"];
$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.tours.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "tours_filter",
		"IBLOCK_ID" => "18",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "modern",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "POINT_DEPARTURE",
			2 => "TOWN",
			3 => "ROUTE",
			4 => "DEPARTURE",
			5 => "DEPARTURE_TEXT",
			6 => "FOOD",
			7 => "DAYS",
			8 => "DEPARTURE_EXC_TEXT",
			9 => "DURATION",
			10 => "DURATION_TIME",
			11 => "TOURTYPE",
			12 => "TRANSPORT",
			13 => "TYPE_EXCURSIONS",
			14 => "THEME_TOURS",
			15 => "NMAN",
			16 => "SIGHTS",
			17 => "EXCURSIONS",
			18 => "HOTEL",
			19 => "PRICE",
			20 => "PRICE_CHILD",
			21 => "CURRENCY",
			22 => "DISCOUNT",
			23 => "ADDITIONAL",
			24 => "TOUR_TYPE",
			25 => "NEW",
			26 => "MT_ID",
			27 => "PRICE_INCLUDE",
			28 => "PRICE_NO_INCLUDE",
			29 => "MEDICINE",
			30 => "DOCUMENT",
			31 => "SHOW_ON_MAIN",
			32 => "TYPE_PERMIT",
			33 => "NDAYS",
			34 => "BYR_PRICE",
			35 => "CHILDREN_PROG",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => "seo.tours.list",
		"ADD_PROPERTY_95" => "69",
		"ADD_PROPERTY_96" => "-",
		"ADD_PROPERTY_101" => "-",
		"ADD_PROPERTY_182" => "-",
		"ADD_PROPERTY_102" => "-",
		"ADD_PROPERTY_ID" => array(
		),
		"ADD_PROPERTY_97_min" => "",
		"ADD_PROPERTY_97_max" => "",
		"ADD_PROPERTY_110" => "N",
		"ADD_PROPERTY_479" => "179",
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>