<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/otdykh-v-belarusi/bazy-otdykha-i-agrousadby/");
$APPLICATION->SetPageProperty("title", "Отдых в Белоруссии зимой. Зимний отдых в Беларуси, цены - ЦЕНТРКУРОРТ");
$APPLICATION->SetPageProperty("description", "Полный перечень баз отдыха Беларуси. Описание, цены на путевки.");
$APPLICATION->SetTitle("Базы отдыха и агроусадьбы");
?>
    <div id="search-forms-iframe-block-693"><span>Идет загрузка формы поиска...</span></div>
    <script src="https://vetliva.ru/travelsoft.pm/assets/js/bundles/init.js"></script>
    <script>
        Travelsoft.init({
            afterLoadingPage: false,
            forms: {
                insertion_id: "search-forms-iframe-block-693",
                types: ["placements"],
                active: "placements",
                url: ["https://www.otpusk.by/otdykh-v-belarusi/gostinnitsy/searchresult.php"],
                selectIframeCss: "",
                datepickerIframeCss: "",
                childrenIframeCss: "",
                mainIframeCss: ".btn-search-area button:hover{background-color: #EB5019 !important;border-color: #EB5019;} .btn-search-area button{border-radius: 0 !important; background: #EB5019;border-color: #EB5019;} label{color: #fff;} .form-control{border-radius: 0} .nav-tabs{display: none !important;} body{ background-color:#286090 !important}\t.form-group {margin-bottom: 0px;}.col-md-3, .col-sm-6 {padding-right: 10px;padding-left: 10px;}.tab-content {margin-top: 10px;}label {color: #fff;font-size: 11px;font-weight: normal;}.form-control {cursor: pointer;overflow: hidden;display: inline-block;line-height: 27px !important;height: 40px;border: 0px solid #ccc;}.btn-primary{-webkit-transition:all .3s;-o-transition:all .3s;transition:all .3s;text-transform:uppercase;font-size:13px;letter-spacing:2px;line-height:1;padding:11px 20px;border-width:2px}.container{width: 100%;}"
            }
        });
    </script>


<h2 style="text-align: justify;">Базы отдыха Беларуси<br>
 </h2>
<p style="text-align: justify;">
</p>
<p style="text-align: justify;">
	 <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section",
	"seo.hotels.list",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "136",
		"ADD_PROPERTY_61" => "69",
		"ADD_PROPERTY_62" => "-",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "seo.hotels.list",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(0=>"COUNTRY",1=>"TOWN",2=>"TYPE_ID",3=>"CAT_ID",4=>"HD_ADDRESS",5=>"HD_ADDRESS_COUNTRY_LANGUAGE",6=>"HD_PHONE",7=>"HD_FAX",8=>"HD_EMAIL",9=>"HD_HTTP",10=>"MAP",11=>"CURRENCY_BY",12=>"PRICE_MIN_BY",13=>"PRICE_MIN_RU",14=>"CURRENCY_RU",15=>"MAP_SCALE",16=>"SEARCH",17=>"VIDEO",18=>"MEDPROFIL",19=>"NATIONAL_PARK",20=>"HD_DESC",21=>"PROEZD",22=>"SPORTS_COMPLEX",23=>"PRICE_TEXT",24=>"HD_DESCROOM",25=>"HD_DESCMEAL",26=>"HD_DESCSERVICE",27=>"HD_DESCSPORT",28=>"HD_DESCSHEALTH",29=>"HD_DESCCHILD",30=>"HD_DESCBEACH",31=>"MEDICAL_TREATMENT",32=>"TYPE_PERMIT",33=>"HD_ADDINFORMATION",34=>"TYPE",35=>"",),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(0=>"",1=>"",),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N"
	)
);?>
</p>
<p>
</p>
<h4>Агроусадьбы Беларуси</h4>
 <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.hotels.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "137",
		"ADD_PROPERTY_61" => "69",
		"ADD_PROPERTY_62" => "-",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter2",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "TOWN",
			2 => "TYPE_ID",
			3 => "CAT_ID",
			4 => "HD_ADDRESS",
			5 => "MT_HOTELKEY",
			6 => "HD_ADDRESS_COUNTRY_LANGUAGE",
			7 => "HD_PHONE",
			8 => "HD_FAX",
			9 => "HD_EMAIL",
			10 => "HD_HTTP",
			11 => "MAP",
			12 => "CURRENCY_BY",
			13 => "PRICE_MIN_BY",
			14 => "PRICE_MIN_RU",
			15 => "CURRENCY_RU",
			16 => "MAP_SCALE",
			17 => "SEARCH",
			18 => "VIDEO",
			19 => "MEDPROFIL",
			20 => "MT_KEY",
			21 => "CONFERENCE_HALL",
			22 => "NATIONAL_PARK",
			23 => "NOT_SHOW_MT",
			24 => "REGIONS",
			25 => "HD_DESC",
			26 => "PROEZD",
			27 => "SPORTS_COMPLEX",
			28 => "CANCELLATION",
			29 => "RF_PRICE_TYPE",
			30 => "FOREIGN_PRICE_TYPE",
			31 => "PRICE_TEXT",
			32 => "HD_DESCROOM",
			33 => "HD_DESCMEAL",
			34 => "HD_DESCSERVICE",
			35 => "HD_DESCSPORT",
			36 => "HD_DESCSHEALTH",
			37 => "HD_DESCCHILD",
			38 => "HD_DESCBEACH",
			39 => "MEDICAL_TREATMENT",
			40 => "TYPE_PERMIT",
			41 => "HD_ADDINFORMATION",
			42 => "",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => "seo.hotels.list"
	),
	false
);?><br>
<h4>Коттеджи</h4>
 <?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.hotels.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_167" => "-",
		"ADD_PROPERTY_60" => "20",
		"ADD_PROPERTY_61" => "69",
		"ADD_PROPERTY_62" => "-",
		"ADD_PROPERTY_63" => "-",
		"ADD_PROPERTY_82" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter3",
		"IBLOCK_ID" => "14",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "TOWN",
			2 => "TYPE_ID",
			3 => "CAT_ID",
			4 => "HD_ADDRESS",
			5 => "MT_HOTELKEY",
			6 => "HD_ADDRESS_COUNTRY_LANGUAGE",
			7 => "HD_PHONE",
			8 => "HD_FAX",
			9 => "HD_EMAIL",
			10 => "HD_HTTP",
			11 => "MAP",
			12 => "CURRENCY_BY",
			13 => "PRICE_MIN_BY",
			14 => "PRICE_MIN_RU",
			15 => "CURRENCY_RU",
			16 => "MAP_SCALE",
			17 => "SEARCH",
			18 => "VIDEO",
			19 => "MEDPROFIL",
			20 => "MT_KEY",
			21 => "CONFERENCE_HALL",
			22 => "NATIONAL_PARK",
			23 => "NOT_SHOW_MT",
			24 => "REGIONS",
			25 => "HD_DESC",
			26 => "PROEZD",
			27 => "SPORTS_COMPLEX",
			28 => "CANCELLATION",
			29 => "RF_PRICE_TYPE",
			30 => "FOREIGN_PRICE_TYPE",
			31 => "PRICE_TEXT",
			32 => "HD_DESCROOM",
			33 => "HD_DESCMEAL",
			34 => "HD_DESCSERVICE",
			35 => "HD_DESCSPORT",
			36 => "HD_DESCSHEALTH",
			37 => "HD_DESCCHILD",
			38 => "HD_DESCBEACH",
			39 => "MEDICAL_TREATMENT",
			40 => "TYPE_PERMIT",
			41 => "HD_ADDINFORMATION",
			42 => "",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "Y",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => "seo.hotels.list"
	),
	false
);?><br>
<p style="text-align: justify;">
	 Базы отдыха в Беларуси – это уютные туристические и развлекательные комплексы в различных частях страны, расположенные обычно в зонах природных заповедников. Они расположены в окружении уникальной природы, мягкого континентального климата, в непосредственной близости от живописных водоемов и густых лиственных массивов нетронутого человеческим вмешательством леса.
</p>
<p style="text-align: justify;">
	 Все базы отдыха представляют собой компактные и очень спокойные городки с домиками-бунгало, виллами или пансионатами, в которых имеются все необходимые для проживания удобства. Каждый номер обеспечивается горячей водой, электричеством, телевидением и интернет-коммуникациями.
</p>
<p style="text-align: justify;">
	 В непосредственной близости от любой базы отдыха в Беларуси находятся развлекательные центры, рестораны и кафе, в зеленой зоне оборудованы места для пикников, шашлыка и барбекю. На базах обеспечивается охрана территории и автостоянок, созданы все условия для отдыха, оздоровления и развлечений.
</p>
<p style="text-align: justify;">
	 Большинство баз отдыха в Беларуси одновременно являются туристическими центрами, которые изобилуют удобными туристическими маршрутами, велосипедными магистралями и клубами конной езды. На базах, которые расположены возле природных водоемов, созданы яхт-клубы и лодочные станции для комфортного отдыха на воде.
</p>
<p style="text-align: justify;">
	 Практически все базы отдыха Беларуси созданы с учетом полноценного семейного и детского отдыха. Руководство баз обычно предлагает детские площадки и городки для игр, анимационные программы и игровые комнаты для малышей. На каждой базе отдыха имеется свой медицинский кабинет со штатными врачами и медсестрами.
</p>
<p style="text-align: justify;">
	 Большинство баз находятся в заповедных уголках природы, добраться до которых не доставит большого труда – все базы связаны автомобильными коммуникациями со столицей, областными центрами и городами регионального подчинения. Для того, чтобы быстро добраться к месту отдыха, вы можете воспользоваться рейсовым транспортом, маршрутным такси или специальными экспресс-такси, идущими непосредственно на базу.
</p>
<p style="text-align: justify;">
	 Для того, чтобы ваш отдых был комфортным, базы отдыха предлагают раннее бронирование. Для этого вам необходимо связаться с нами, уточнить время вашего отдыха и срок пребывания. Большинство баз работают круглый год и готовы принять вас не только в туристический летний сезон – заказать отдых в живописном природном уголке Беларуси вы можете в любое время года, в том числе в период новогодних и рождественских праздников! <br>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>