<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Черногория");
$APPLICATION->SetPageProperty("keywords", "Черногория, Отдых на море");
$APPLICATION->SetPageProperty("description", "Компания \"Центркурорт\" предлагает Туры в Черногорию с отдыхом на море. Отдых для всей семьи, звоните +375 (17) 215-49-49.");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/tury/avtobusnye-tury-s-otdykhom-na-more/chernogoriya/");
$APPLICATION->SetTitle("Автобусные туры с отдыхом на море в Черногорию");
?><?$APPLICATION->IncludeComponent(
	"travelsoft:catalog.section", 
	"seo.tours.list", 
	array(
		"ACTION_VARIABLE" => "action",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_PROPERTY_101" => "515",
		"ADD_PROPERTY_102" => "-",
		"ADD_PROPERTY_110" => "N",
		"ADD_PROPERTY_182" => "-",
		"ADD_PROPERTY_95" => "78",
		"ADD_PROPERTY_96" => "-",
		"ADD_PROPERTY_97_max" => "",
		"ADD_PROPERTY_97_min" => "",
		"ADD_PROPERTY_ID" => array(
		),
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"FILTER_NAME" => "arrFilter",
		"IBLOCK_ID" => "18",
		"IBLOCK_TYPE" => "otpusk",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "3",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_LIMIT" => "5",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "30",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(
			0 => "DURATION",
			1 => "DURATION_TIME",
			2 => "NMAN",
			3 => "PRICE",
			4 => "PRICE_CHILD",
			5 => "MT_ID",
			6 => "MT_KEY",
			7 => "DURATION_DAYS",
			8 => "BYR_PRICE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array(
			0 => "COUNTRY",
			1 => "POINT_DEPARTURE",
			2 => "TOWN",
			3 => "DEPARTURE",
			4 => "FOOD",
			5 => "DAYS",
			6 => "PROVIDER",
			7 => "TOURTYPE",
			8 => "TRANSPORT",
			9 => "TYPE_EXCURSIONS",
			10 => "THEME_TOURS",
			11 => "SIGHTS",
			12 => "EXCURSIONS",
			13 => "HOTEL",
			14 => "CURRENCY",
			15 => "TOUR_TYPE",
			16 => "NEW",
			17 => "FREE",
			18 => "SHOW_ON_MAIN",
			19 => "SALE",
			20 => "TYPE_PERMIT",
			21 => "PRICE_FOR",
			22 => "TOUR_IN_ARCHIVE",
			23 => "NDAYS",
		),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROPERTY_CODE" => array(
			0 => "COUNTRY",
			1 => "POINT_DEPARTURE",
			2 => "TOWN",
			3 => "ROUTE",
			4 => "DEPARTURE",
			5 => "DEPARTURE_TEXT",
			6 => "FOOD",
			7 => "DAYS",
			8 => "PROVIDER",
			9 => "DEPARTURE_EXC_TEXT",
			10 => "DURATION",
			11 => "DURATION_TIME",
			12 => "TOURTYPE",
			13 => "TRANSPORT",
			14 => "TYPE_EXCURSIONS",
			15 => "THEME_TOURS",
			16 => "NMAN",
			17 => "SIGHTS",
			18 => "EXCURSIONS",
			19 => "HOTEL",
			20 => "PRICE",
			21 => "PRICE_CHILD",
			22 => "CURRENCY",
			23 => "DISCOUNT",
			24 => "HD_DESC",
			25 => "ADDITIONAL",
			26 => "TOUR_TYPE",
			27 => "NEW",
			28 => "FREE",
			29 => "MT_ID",
			30 => "PRICE_INCLUDE",
			31 => "PRICE_NO_INCLUDE",
			32 => "DOCUMENT",
			33 => "MT_KEY",
			34 => "DURATION_DAYS",
			35 => "MEDICINE",
			36 => "SHOW_ON_MAIN",
			37 => "SALE",
			38 => "TYPE_PERMIT",
			39 => "PRICE_FOR",
			40 => "TOUR_IN_ARCHIVE",
			41 => "NDAYS",
			42 => "BYR_PRICE",
			43 => "",
		),
		"SECTION_CODE" => "",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array(
			0 => "",
			1 => "",
		),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"COMPONENT_TEMPLATE" => "seo.tours.list",
		"FILE_404" => ""
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>