<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("canonical", "https://www.otpusk.by/tury/avtobusnye-tury/");
$APPLICATION->SetPageProperty("title", "Автобусные туры из Минска в Европу. Экскурсионные автобусные туры, цены");
$APPLICATION->SetTitle("Автобусные туры");
?>

<?$APPLICATION->IncludeComponent(
    "travelsoft:catalog.section",
    "bus-tours-list",
    Array(
        "ACTION_VARIABLE" => "",
        "ADD_PICT_PROP" => "-",
        "ADD_PROPERTIES_TO_BASKET" => "N",
        "ADD_PROPERTY_101" => "515",
        "ADD_PROPERTY_102" => "-",
        "ADD_PROPERTY_110" => "N",
        "ADD_PROPERTY_182" => "-",
        "ADD_PROPERTY_95" => "-",
        "ADD_PROPERTY_96" => "-",
        "ADD_PROPERTY_97_max" => "",
        "ADD_PROPERTY_97_min" => "",
        "ADD_PROPERTY_ID" => array(),
        "ADD_SECTIONS_CHAIN" => "N",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "N",
        "BACKGROUND_IMAGE" => "-",
        "BASKET_URL" => "",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "N",
        "DETAIL_URL" => "",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "ELEMENT_SORT_FIELD" => "SORT",
        "ELEMENT_SORT_FIELD2" => "timestamp_x",
        "ELEMENT_SORT_ORDER" => "ASC",
        "ELEMENT_SORT_ORDER2" => "desc",
        "FILTER_NAME" => "arrFilter",
        "IBLOCK_ID" => "18",
        "IBLOCK_TYPE" => "otpusk",
        "INCLUDE_SUBSECTIONS" => "Y",
        "LABEL_PROP" => "-",
        "LINE_ELEMENT_COUNT" => "",
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "",
        "MESS_BTN_BUY" => "",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_SUBSCRIBE" => "",
        "MESS_NOT_AVAILABLE" => "",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "OFFERS_LIMIT" => "0",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "modern",
        "PAGER_TITLE" => "",
        "PAGE_ELEMENT_COUNT" => "10",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(),
        "PRICE_VAT_INCLUDE" => "N",
        "PRODUCT_ID_VARIABLE" => "",
        "PRODUCT_PROPERTIES" => array(""),
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "",
        "PROPERTY_CODE" => array("COUNTRY","POINT_DEPARTURE","TOWN","DEPARTURE","DEPARTURE_TEXT","FOOD","DAYS","TOURTYPE","TRANSPORT","TYPE_EXCURSIONS","HOTEL","PRICE","CURRENCY","DISCOUNT","ADDITIONAL","TOUR_TYPE","NEW","FREE","MT_ID","PRICE_INCLUDE","PRICE_NO_INCLUDE","DOCUMENT","MT_KEY","MEDICINE","PRICE_FOR","NDAYS","DAILY","ACCOMODATIONS","FILE","TOUR_IN_ARCHIVE",""),
        "SECTION_CODE" => "",
        "SECTION_ID" => "",
        "SECTION_ID_VARIABLE" => "",
        "SECTION_URL" => "",
        "SECTION_USER_FIELDS" => array("",""),
        "SEF_MODE" => "N",
        "SET_BROWSER_TITLE" => "N",
        "SET_LAST_MODIFIED" => "N",
        "SET_META_DESCRIPTION" => "N",
        "SET_META_KEYWORDS" => "N",
        "SET_STATUS_404" => "N",
        "SET_TITLE" => "N",
        "SHOW_404" => "N",
        "SHOW_ALL_WO_SECTION" => "Y",
        "SHOW_PRICE_COUNT" => "",
        "TEMPLATE_THEME" => "",
        "USE_MAIN_ELEMENT_SECTION" => "N",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N"
    )
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>